Multiple hooks
hupe1980/react-script-hook pull request #28
Opened 2021-12-12 17:25 UTC by edemaine

Following the plan discussed in #27, I ended up with a hybrid of the two approaches:
* Like Approach 2, I added a map `scripts` from `src` URL to current status of the script loading (`loading` and `error`) along with the associated `scriptEl`.
* Like Approach 1, if multiple hooks depend on the same script, they'll each register a `load` and `error` event handler. This seemed simpler than accumulating a list of `setLoad` and `setError` handlers (instead using existing listener system), and multiple components using the same script is probably an edge-case anyway.

The map `scripts` is exported in case someone removes a `<script>` tag and needs to reload it (which we need in testing in particular). This is arguably a downside / incompatibility of this approach (and anything based on Approach 2): it's possible for the DOM's `<script>` tags to deviate from our cached knowledge in `scripts`, by manually removing a `<script>` from the DOM after it's added by this hook. I can't think of a setting where that's important (except in testing): presumably, the code has already run, and all of its side effects remain in effect.

The end result is that this PR:
* Correctly handles multiple hooks from different components with same `src` (fix #27). Only one of the hook calls will add the tag (even without `checkForExisting`), and both will receive "loaded" status when the script loads.
* Sets "loaded" status immediately if an existing `<script>` tag is found via `checkForExisting` (fix #24). The DOM gets checked upon initial load, instead of inside the `useEffect`; the result gets cached, so this shouldn't happen more than once.

(These changes are each done in separate commits, in case that's useful.)

2021-12-16 21:29 UTC, hupe1980 requested changes
I couldn't get the hook working. I always get a invalid hook call warning https://reactjs.org/warnings/invalid-hook-call-warning.html. Do I have to pay attention to anything else?

2021-12-17 19:49 UTC, edemaine commented on src/use-script.tsx
> +        const existing: HTMLScriptElement | null = document.querySelector(
This is a good point.  I've added a condition of `isBrowser` here as well.  (Sorry, I don't have any SSR examples handy, so didn't test SSR.)

2021-12-17 19:51 UTC, edemaine commented
Thanks for taking a look!

> I always get a invalid hook call warning https://reactjs.org/warnings/invalid-hook-call-warning.html. Do I have to pay attention to anything else?

May I ask how you're testing? I had the exact same issue when using my branch via `npm link`. My best guess is that this is caused by multiple `react` deps (even though the versions were the same in my case). I got it working by instead changing the dependency in `package.json` as follows:

```
  "react-script-hook": "github:edemaine/react-script-hook#multiple-hooks",
```

Could you check whether this works for you? It's still mysterious to me why `npm link` didn't work...

2021-12-18 14:04 UTC, hupe1980 commented
Understood. I'll try again. I also used npm link.

2021-12-19 20:31 UTC, hupe1980 commented
I could test it now. NPM link works if you delete the node_modules folder after the build.

```typescript
useScript({ src: 'https://js.stripe.com/v3/', checkForExisting: true });
useScript({ src: 'https://js.stripe.com/v3/', checkForExisting: true });
useScript({ src: 'https://js.stripe.com/v3/', checkForExisting: true });
```
I got
```html
<script src="https://js.stripe.com/v3/"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="https://js.stripe.com/v3/"></script>
```
checkForExisting doesn't seem to be working properly yet

2021-12-21 15:35 UTC, edemaine commented
Thanks for finding this! I've added a test for this case (multiple hooks in the same component) and hopefully fixed all related bugs, by rechecking both `scripts[src]` and the DOM (if `checkForExisting`) when the effect fires &mdash; I forgot that everything could change between mount and the effect callback.

2022-01-11 20:44 UTC, hupe1980 commented
This time it worked. However, it now looks like the checkForExisting parameter is obsolete. Even if it is false, the script is only added once. What do you think about that? Can we remove the parameter?

2022-01-11 20:54 UTC, edemaine commented
In the current code, there is a slight difference. If `checkForExisting` is false, the DOM isn't checked, so the script may be added again if it was there for some other reason (e.g. initial page load, or another piece of software). I'm not sure whether that is functionality worth preserving; probably, if we're about to change the DOM, it doesn't cost much more to also check the DOM. If you agree, we could force `checkForExisting` to true.

2022-01-11 21:09 UTC, hupe1980 commented
Oh yes right. Then I would say that the parameter still makes sense after all.

2022-01-11 21:12 UTC, hupe1980 approved these changes
LGTM. Thx

2022-01-11 21:13 UTC, merged